### ISSUE TITLE
No easy way to initialize wallet widget in Testnet mode

### ISSUE THREAD

**Issue by fomalsd** [0xsequence/web3-unreal-sdk#3]
Environment: webview inside UE 5.0.3 editor, no cache or cookies present
Testnet

While `sequence.app/auth?mode=testnet` URL works for browser, Unreal widget only has `Wallet App URL` field that is passed to some JS init code, ignoring network mode part

Things tried:
- `polygon` is set as network and `Enable Testnet` is then clicked inside the widget:
Login never works, black screen is shown with the following error: `unable to set default network as chain 'polygon' does not exist`

- `mumbai` is set as network and `Enable Testnet` is then clicked inside the widget:
Login works ONLY when a browser used to click the confirm link already visited sequence.app before and had `Enable Testnet` clicked on (see #2).

**Comment by arilotter** [comment]
Passing a test network should now switch the wallet to the correct mode automatically :)

**Comment by fomalsd** [comment]
it's still a thing – if wallet widget is in testnet mode and you attempt to confirm login from a phone (without visiting sequence website and turning testnet on first) then the login confirmation will never complete
